# Using GitLab CI for GitHub repo.
# Author: Jintao Zhang <zhangjintao9020@gmail.com>
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH

stages:
  - build-latest
  - build-normal

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

.build_template: &build_definition
  script:
    - IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - '[[ $CI_COMMIT_REF_SLUG = master ]] && IMAGE_TAG=latest || IMAGE_TAG=$CI_COMMIT_REF_SLUG'
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker images
    - docker push "$IMAGE_NAME:$IMAGE_TAG"


build-latest:
  stage: build-latest
  <<: *build_definition
  only:
    - master

build-normal:
  stage: build-normal
  <<: *build_definition
  except:
    - master

after_script:
  - docker logout $CI_REGISTRY
