language: bash
services: docker

env:
  - VARIANT=stretch/slim

before_install:
  - env | sort
  - slash='/'; image="vim:${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
